# Generated by Django 4.1.3 on 2022-11-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_api', '0002_alter_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('age', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
